module.exports = [
  { fullName: 'Ahmad Faizal', email: 'ahmad.faizal@example.com', phone: '012-3456789', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Nur Aisyah', email: 'nur.aisyah@example.com', phone: '013-4567890', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Mohd Hakim', email: 'mohd.hakim@example.com', phone: '014-5678901', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Siti Mariam', email: 'siti.mariam@example.com', phone: '015-6789012', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Aiman Syafiq', email: 'aiman.syafiq@example.com', phone: '016-1112233', gender: 'Male', membershipType: 'Silver' },
  { fullName: 'Nabila Sofea', email: 'nabila.sofea@example.com', phone: '017-2223344', gender: 'Female', membershipType: 'Bronze' },
  { fullName: 'Farhan Zulkifli', email: 'farhan.zulkifli@example.com', phone: '018-3334455', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Aina Natasha', email: 'aina.natasha@example.com', phone: '019-4445566', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Hafizuddin', email: 'hafizuddin@example.com', phone: '011-5556677', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Izzati Khairunnisa', email: 'izzati.khairunnisa@example.com', phone: '012-6667788', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Lee Wei Ming', email: 'lee.weiming@example.com', phone: '013-7778899', gender: 'Male', membershipType: 'Silver' },
  { fullName: 'Tan Mei Ling', email: 'tan.meiling@example.com', phone: '014-8889900', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Chong Li Wei', email: 'chong.liwei@example.com', phone: '015-9990011', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Lim Jia Hui', email: 'lim.jiahui@example.com', phone: '016-1212121', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Wong Kai Jun', email: 'wong.kaijun@example.com', phone: '017-2323232', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Ng Pei Xin', email: 'ng.peixin@example.com', phone: '018-3434343', gender: 'Female', membershipType: 'Bronze' },
  { fullName: 'Lau Jun Hao', email: 'lau.junhao@example.com', phone: '019-4545454', gender: 'Male', membershipType: 'Silver' },
  { fullName: 'Ho Yan Ling', email: 'ho.yanling@example.com', phone: '011-5656565', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Ong Zhi Wei', email: 'ong.zhiwei@example.com', phone: '012-6767676', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Teo Mei Yin', email: 'teo.meiyin@example.com', phone: '013-7878787', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Arun Kumar', email: 'arun.kumar@example.com', phone: '014-8989898', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Anita Devi', email: 'anita.devi@example.com', phone: '015-9090909', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Rajesh Singh', email: 'rajesh.singh@example.com', phone: '016-1010101', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Priya Nair', email: 'priya.nair@example.com', phone: '017-2020202', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Suresh Raman', email: 'suresh.raman@example.com', phone: '018-3030303', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Kavitha Subramaniam', email: 'kavitha.subramaniam@example.com', phone: '019-4040404', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Vijay Anand', email: 'vijay.anand@example.com', phone: '011-5050505', gender: 'Male', membershipType: 'Silver' },
  { fullName: 'Shalini Gupta', email: 'shalini.gupta@example.com', phone: '012-6060606', gender: 'Female', membershipType: 'Bronze' },
  { fullName: 'Ravi Shankar', email: 'ravi.shankar@example.com', phone: '013-7070707', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Deepa Iyer', email: 'deepa.iyer@example.com', phone: '014-8080808', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Daniel Wong', email: 'daniel.wong@example.com', phone: '015-9091919', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Alyssa Lim', email: 'alyssa.lim@example.com', phone: '016-1122334', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Muhammad Irfan', email: 'muhammad.irfan@example.com', phone: '017-2233445', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Nur Huda', email: 'nur.huda@example.com', phone: '018-3344556', gender: 'Female', membershipType: 'Gold' },
  { fullName: 'Jason Tan', email: 'jason.tan@example.com', phone: '019-4455667', gender: 'Male', membershipType: 'Silver' },
  { fullName: 'Meera Patel', email: 'meera.patel@example.com', phone: '011-5566778', gender: 'Female', membershipType: 'Bronze' },
  { fullName: 'Adam Hakimi', email: 'adam.hakimi@example.com', phone: '012-6677889', gender: 'Male', membershipType: 'Gold' },
  { fullName: 'Samantha Lee', email: 'samantha.lee@example.com', phone: '013-7788990', gender: 'Female', membershipType: 'Silver' },
  { fullName: 'Iskandar Zainal', email: 'iskandar.zainal@example.com', phone: '014-8899001', gender: 'Male', membershipType: 'Bronze' },
  { fullName: 'Pooja Sharma', email: 'pooja.sharma@example.com', phone: '015-9900112', gender: 'Female', membershipType: 'Gold' },
];
